version: "3"

services:
  gitea:
    image: gitea/gitea:1.12
    restart: unless-stopped
    volumes:
      - gitea_data:/var/lib/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/gitea
      - ./config/app.ini:/data/gitea/conf/app.ini
    ports:
      - "3000:3000"
      - "222:222"
    networks:
      - backend
    environment:
      - USER_UID=1001
      - USER_GID=1002
      - GITEA__DEFAULT__RUN_MODE=${GITEA__DEFAULT__RUN_MODE}
      - GITEA__server__DOMAIN=${GITEA__server__DOMAIN}
      - GITEA__server__SSH_DOMAIN=${GITEA__server__SSH_DOMAIN}
      - GITEA__server__SSH_PORT=${GITEA__server__SSH_PORT}
      - GITEA__database__HOST=${GITEA__database__HOST}
      - GITEA__database__NAME=${GITEA__database__NAME}
      - GITEA__database__USER=${GITEA__database__USER}
      - GITEA__database__PASSWD=${GITEA__database__PASSWD}
      - GITEA__security__SECRET_KEY=${GITEA__security__SECRET_KEY}
      - GITEA__security__INTERNAL_TOKEN=${GITEA__security__INTERNAL_TOKEN}
      - GITEA__service__REGISTER_EMAIL_CONFIRM=${GITEA__service__REGISTER_EMAIL_CONFIRM}
      - GITEA__mailer__ENABLED=${GITEA__mailer__ENABLED}
      - GITEA__mailer__HOST=${GITEA__mailer__HOST}
      - GITEA__mailer__USER=${GITEA__mailer__USER}
      - GITEA__mailer__PASSWD=${GITEA__mailer__PASSWD}
      - GITEA__mailer__FROM=${GITEA__mailer__FROM}
      - GITEA__oauth2__JWT_SECRET=${GITEA__oauth2__JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 10s

  db:
    image: mariadb:10.11
    restart: unless-stopped
    command: mariadbd --innodb-buffer-pool-size=${MARIADB_INNODB_BUFFER_POOL_SIZE}
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
      - db_backup_data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      start_period: 5s
  util:
    image: ubuntu:22.04
    entrypoint: bash -c 'while :; do :; done & kill -STOP $! && wait $!'
    volumes:
      - db_data:/var/lib/mysql
      - gitea_data:/var/lib/gitea
      - db_backup_data:/docker-entrypoint-initdb.d
      - ./:/dotslash

    tty: true
    networks:
      - backend

volumes:
  gitea_data:
  db_data:
  db_backup_data:

networks:
  backend:
